services:
  quant_sentiment:
    image: mayberry4477/quant_sentiment:latest
    restart: "unless-stopped"
    environment:
      DATABASE_URL: 
      API_LISTEN_ADDRESS: 0.0.0.0
      API_PORT: "8017"
    ports:
      - "8017:8017"
